"""empty message

Revision ID: 56ddd4c1a9ea
Revises: 
Create Date: 2021-04-17 16:58:04.383801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ddd4c1a9ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMAIL', 'UNKNOW', name='genderenum'), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('working_age', sa.Integer(), nullable=True),
    sa.Column('education', sa.Enum('DOCTOR', 'MASTER', 'BACHELOR', 'HIGHSCHOOL', 'MIDDLESCHOOL', 'UNKNOW', name='educationenum'), nullable=True),
    sa.Column('certificate', sa.String(length=1000), nullable=True),
    sa.Column('resume_score', sa.Integer(), nullable=True),
    sa.Column('interview_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('hr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hr_id'], ['hr_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('project')
    op.drop_table('hr_user')
    # ### end Alembic commands ###
