"""empty message

Revision ID: fbd3f86e427f
Revises: 56ddd4c1a9ea
Create Date: 2021-04-17 17:05:01.189041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd3f86e427f'
down_revision = '56ddd4c1a9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_user', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hr_user', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hr_user', type_='foreignkey')
    op.drop_column('hr_user', 'project_id')
    # ### end Alembic commands ###
